### ISSUE TITLE
Disbursement On Schedule

### ISSUE THREAD

**Issue by xanderdunn** [numerai/contract#13]
Peter suggests instead of resetting the disbursement every week, be able to mint the amount that should be available by the second.

Currently, missing a mint() in a given week prevents us from being able to get back on schedule with total supply.

**Comment by philipcmonk** [comment]
Do we always intend to mint the entire weekly disbursement amount?  If not, this will leave an increasing amount of mintable NMR, which doesn't feel right.

**Comment by xanderdunn** [comment]
We do intend to always mint the entire mintable amount.  We don't intend to stray from the total supply schedule outlined in the whitepaper.  This is important because it has ramifications for how people value Numeraire.

**Comment by philipcmonk** [comment]
I don't see a schedule in the whitepaper, but as written the contract allows the minting of no more than ~96,153 NMR/week, but the timing is reset on the mint call, so we'll slowly drift throughout the week.

Is the ~96,153 NMR/week number correct?

**Comment by xanderdunn** [comment]
Yeah, the whitepaper mentions the total max and that "the smart contract will mint
a fixed number of Numeraire each week until the maximum is reached".  The number in the contract is right.

**Comment by philipcmonk** [comment]
Sounds good.  The clock should start ticking the moment the contract is deployed, right?

**Comment by xanderdunn** [comment]
That sounds right
