### ISSUE TITLE
Can't test ("could not find artifacts for ./Migrations.sol")

### ISSUE THREAD

**Issue by philipcmonk** [numerai/contract#15]
`truffle test` crashes with error:

```
Error: Could not find artifacts for ./Migrations.sol from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/node_modules/truffle-resolver/index.js:37:9)
    at TestResolver.require (/usr/local/lib/node_modules/truffle/lib/testing/testresolver.js:17:30)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/node_modules/truffle-migrate/resolverintercept.js:14:32)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-migrate/index.js:55:33
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

What am I missing?

**Comment by philipcmonk** [comment]
I copied a fresh `Migrations.sol` and `1_initial_migration.js` from `truffle init`, and I was able to run `truffle test`.  However, it crashed with a "could not unlock signer account" error on the "before" hook (so it didn't run any other tests).

Should those two files be added in this manner?  Or is that causing the tests to fail?

**Comment by philipcmonk** [comment]
Ah, the crash was due to an incorrect `testrpc` command line (omitted the last character).

**Comment by philipcmonk** [comment]
Whoops, didn't mean to push that directly to master

**Comment by ltfschoen** [comment]
I got this error when the the filename of my Solidity contract (i.e. `MappingUserBalances.sol`) didn't match the name of the contract contained within that file (i.e. I had `contract MappingUser { ... }` instead of `contract MappingUserBalances { ... }`)

**Comment by chuacw** [comment]
I got this error after deleting Migrations.sol from the contracts directory.

**Comment by ChanForPres** [comment]
@ltfschoen You're a lifesaver! Been pulling hair for hours..

**Comment by vineettyagi28** [comment]
@ltfschoen You save my day. Thanks a lot.

**Comment by fidenz-chim** [comment]
This solved the problem and thanks!  But looks like we could have one contract per .sol

**Comment by aaroncolwill** [comment]
I also got this error after deleting Migrations.sol

**Comment by ZixiaoWang** [comment]
+1, once I deleted my Migrations.sol. This error kept popping up.

**Comment by psy21d** [comment]
@ltfschoen 
Ну и тупорылая ошибка. В жизни бы сам никогда не нашёл в чём там проблема!
Исправил, всё работает. Разработчики индюки.

Exactly same problem, that fix by rename contract function itself.

**Comment by psy21d** [comment]
Migrations.sol not found?
But his name is NOT listed in files at all.
Whats a feyking problem?
This is just, for what?
Why I can not to delete them safely?

**Comment by HGBG** [comment]
@ltfschoen great observation Sir :) saved my time, thanks!

**Comment by alacret** [comment]
Make sure you have the Migrations.sol and that the name of the contract is the same as the name of the file, that solved the issue for me

**Comment by uWinkel** [comment]
If you have the correct name set and it the error still occurs, another possible fix is to delete all the Contract Interface .json files in your contracts build directory. You can set the folder in your truffle js file with 
` contracts_build_directory: path.join(__dirname, "your/path")
`
