### ISSUE TITLE
Events declared but not used

### ISSUE THREAD

**Issue by philipcmonk** [numerai/contract#16]
NumeraireShared defines the `TournamentCreated` and `RoundCreated` events, but they are never fired.  Should they be fired in NumeraireBackend `createTournament()` and `createRound()`, respectively?

**Comment by philipcmonk** [comment]
For that matter, why does `StakeCreated` reference the parent round and tournament, but `RoundCreated` does not reference the parent tournament?

Is there a point to including the number of rounds initially in a created tournament, since this will always be zero?  Same for stakes in rounds.

**Comment by xanderdunn** [comment]
Yes, the events should be fired.  Fix that.

**Comment by xanderdunn** [comment]
It's worth referencing the parent tournament in a `RoundCreated` event.

**Comment by xanderdunn** [comment]
Yeah, sending the numRounds in a `TournamentCreated` event makes no sense.  Should always be 0.  Remove it.
