### ISSUE TITLE
Consider distinguishing between key security levels

### ISSUE THREAD

**Issue by philipcmonk** [numerai/contract#41]
As discussed in section 6.2.1 of the security audit, we should consider using a system where commonly-used medium-security keys are used for most things (where we currently use `onlyOwner`), and high-security keys are required for those things that we currently use multisig for.

**Comment by xanderdunn** [comment]
This is exactly what we will be doing, as you've described with `onlyOwner` and `onlyManyOwners`.  What's the difference in this proposal?

**Comment by philipcmonk** [comment]
Currently, there is a single set of owner keys.  Any owner can perform any of the `onlyOwner` functions while at least `n` of them are required for the `onlyManyOwners` functions.  The proposal is to keep two separate sets of keys.  In the first set are the hot keys, and any one of them would unlock the `onlyOwner` functions.  In the second set are the cold keys, and at least `n` of them would unlock the `onlyManyOwners` functions.  In this way, the compromise of a hot key doesn't reduce the number of cold keys that would need to be compromised.

**Comment by philipcmonk** [comment]
We've decided against doing this.
