### ISSUE TITLE
Shouldn't be destructible

### ISSUE THREAD

**Issue by philipcmonk** [numerai/contract#48]
As discussed in 7.2 of the security audit, there's no reason for us to be destructible, and it could potentially cause problems.

**Comment by philipcmonk** [comment]
Only the delegate contract is destructible, which I think gets around all of the concerns mentioned in 7.2 of the security audit, but why is the delegate destructible anyway?  I'm just not sure it's necessary.

**Comment by xanderdunn** [comment]
The idea with the delegate being destructible is that we can replace it, and the old one could be destroyed.  Perhaps to release ether?  It's not an important feature.

**Comment by philipcmonk** [comment]
The delegate can be changed without it being destructible.  In general, the delegate shouldn't have any ether (it should all be handled in the backend contract), but the security audit cites Peterson's law:  "Tokens will be sent to the most inconvenient address possible."  We mostly handle that by adding `claimTokens` to the backend contract, but if someone were to dig out the delegate address and send ether or tokens there, it wouldn't be accessible unless we either add a `claimTokens` to the delegate or let it be destructible, which would allow us to salvage the ether only at the cost of destroying the contract (tokens wouldn't be salvageable).

I could flip a coin on this one.  It feels good to clean up after ourselves, but I'm not sure it's worth the (very small) additional complexity.  If we actually care about people errantly sending ether/tokens to the delegate, we should add a `claimTokens` to the delegate (I think it can just be moved to the shared contract, but I'd have to think through how `numerai` is defined there).

**Comment by xanderdunn** [comment]
We're removing destructible
