### ISSUE TITLE
Confidence Should Have Only Two Decimals

### ISSUE THREAD

**Issue by xanderdunn** [numerai/contract#68]
Add to the README that confidence will be interpreted as follows: 
Confidence has only 2 decimals, so the minimum confidence increase, as well as the minimum confidence, are 0.01.

This means, a contract call to `stake` would take a confidence of `130` if you wanted to stake with a confidence of `1.30`.

**Comment by dhj-io** [comment]
I think two decimals is too coarse for an NMR value around $100/NMR.  That puts minimum confidence at p=0.5 and just a few levels between 0.5 and 0.9.  Even as you get up around p = 0.9 the increments are over 1%.

**Comment by philipcmonk** [comment]
I agree that 3 decimals sounds about right.
